name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    if: github.actor_id != 210085057
    runs-on: ubuntu-latest
    steps:
      - name: Install zip
        run: sudo apt install zip

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest


      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}


      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: web

      - name: Run build script
        run: bun run build
        working-directory: web


      - name: Bundle files
        run: |
          mkdir -p ./temp/ox_inventory/web
          cp ./{server.lua,README.md,LICENSE,fxmanifest.lua,client.lua,init.lua} ./temp/ox_inventory
          cp -r ./{modules,data,locales} ./temp/ox_inventory
          cp -r ./web/build ./temp/ox_inventory/web/build
          cp -r ./web/images ./temp/ox_inventory/web/images
          cd ./temp && zip -r ../ox_inventory.zip ./ox_inventory

      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: ox_inventory.zip
